image: docker:19.03.0

stages:
  - build

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

Build:
  stage: build
  script:
#    - docker pull $CI_REGISTRY_IMAGE:basic
    - >
      docker build
      --pull
      --build-arg VCS_URL=$CI_PROJECT_URL
#      --cache-from $CI_REGISTRY_IMAGE:basic
      --file=./Dockerfile-basic
      --tag $CI_REGISTRY_IMAGE:basic
      .
    - docker push $CI_REGISTRY_IMAGE:basic
